classdef OldSliceWithTwoGreenLeds < symphonyui.core.descriptions.RigDescription
    
    methods
        
        function obj = OldSliceWithTwoGreenLeds()
            import symphonyui.builtin.daqs.*;
            import symphonyui.builtin.devices.*;
            import symphonyui.core.*;
            import edu.washington.*;
            
            daq = HekaDaqController();
            obj.daqController = daq;
            
            amp1 = MultiClampDevice('Amp1', 1).bindStream(daq.getStream('ao0')).bindStream(daq.getStream('ai0'));
            obj.addDevice(amp1);
            
            red = UnitConvertingDevice('Red LED', 'V').bindStream(daq.getStream('ao1'));
            red.addConfigurationSetting('ndfs', {}, ...
                'type', PropertyType('cellstr', 'row', {'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F12'}));
            red.addResource('ndfAttenuations', containers.Map( ...
                {'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F12'}, ...
                {0.3081, 0.2842, 0.6371, 1.0571, 1.8768, 1.9440, 3.7520, 2.84}));
            red.addConfigurationSetting('gain', '', ...
                'type', PropertyType('char', 'row', {'', 'low', 'medium', 'high'}));
            red.addResource('fluxFactorPaths', containers.Map( ...
                {'low', 'medium', 'high'}, { ...
                riekelab.Package.getCalibrationResource('rigs', 'old_slice', 'red_led_low_flux_factors.txt'), ...
                riekelab.Package.getCalibrationResource('rigs', 'old_slice', 'red_led_medium_flux_factors.txt'), ...
                riekelab.Package.getCalibrationResource('rigs', 'old_slice', 'red_led_high_flux_factors.txt')}));
            red.addConfigurationSetting('lightPath', '', ...
                'type', PropertyType('char', 'row', {'', 'below', 'above'}));
            red.addResource('spectrum', importdata(riekelab.Package.getCalibrationResource('rigs', 'old_slice', 'red_led_spectrum.txt')));
            obj.addDevice(red);
            
            greenFromBelow = UnitConvertingDevice('Green LED from below', 'V').bindStream(daq.getStream('ao2'));
            greenFromBelow.addConfigurationSetting('ndfs', {}, ...
                'type', PropertyType('cellstr', 'row', {'F1', 'F2', 'F3', 'F4', 'F5', 'F8', 'F9', 'F12'}));
            greenFromBelow.addResource('ndfAttenuations', containers.Map( ...
                {'F1', 'F2', 'F3', 'F4', 'F5', 'F8', 'F9', 'F12'}, ...
                {0.3059, 0.2862, 0.5869, 1.0955, 1.9804, 1.8555, 3.6936, 3.6}));
            greenFromBelow.addConfigurationSetting('gain', '', ...
                'type', PropertyType('char', 'row', {'', 'low', 'medium', 'high'}));
            greenFromBelow.addResource('fluxFactorPaths', containers.Map( ...
                {'low', 'medium', 'high'}, { ...
                riekelab.Package.getCalibrationResource('rigs', 'old_slice', 'green_led_low_flux_factors.txt'), ...
                riekelab.Package.getCalibrationResource('rigs', 'old_slice', 'green_led_medium_flux_factors.txt'), ...
                riekelab.Package.getCalibrationResource('rigs', 'old_slice', 'green_led_high_flux_factors.txt')}));
            greenFromBelow.addConfigurationSetting('lightPath', '', ...
                'type', PropertyType('char', 'row', {'', 'below', 'above'}));
            greenFromBelow.addResource('spectrum', importdata(riekelab.Package.getCalibrationResource('rigs', 'old_slice', 'green_led_spectrum.txt')));
            obj.addDevice(greenFromBelow);
            
            % note: this is using all of the information measured for the
            % led from below (spectrum, ndf attenuations); this led should
            % be essentially the same, but at the moment, this rig
            % configuration is being used only for collecting area
            % measurements, where the spectrum and ndf attenuations need
            % not be perfect
            greenFromAbove = UnitConvertingDevice('Green LED from above', 'V').bindStream(daq.getStream('ao3'));
            greenFromAbove.addConfigurationSetting('ndfs', {}, ...
                'type', PropertyType('cellstr', 'row', {'F1', 'F2', 'F3', 'F4', 'F5', 'F8', 'F9', 'F12'}));
            greenFromAbove.addResource('ndfAttenuations', containers.Map( ...
                {'F1', 'F2', 'F3', 'F4', 'F5', 'F8', 'F9', 'F12'}, ...
                {0.3059, 0.2862, 0.5869, 1.0955, 1.9804, 1.8555, 3.6936, 3.6}));
            greenFromAbove.addConfigurationSetting('gain', '', ...
                'type', PropertyType('char', 'row', {'', 'low', 'medium', 'high'}));
            greenFromAbove.addResource('fluxFactorPaths', containers.Map( ...
                {'low', 'medium', 'high'}, { ...
                riekelab.Package.getCalibrationResource('rigs', 'old_slice', 'green_led_low_flux_factors.txt'), ...
                riekelab.Package.getCalibrationResource('rigs', 'old_slice', 'green_led_medium_flux_factors.txt'), ...
                riekelab.Package.getCalibrationResource('rigs', 'old_slice', 'green_led_high_flux_factors.txt')}));
            greenFromAbove.addConfigurationSetting('lightPath', '', ...
                'type', PropertyType('char', 'row', {'', 'below', 'above'}));
            greenFromAbove.addResource('spectrum', importdata(riekelab.Package.getCalibrationResource('rigs', 'old_slice', 'green_led_spectrum.txt')));
            obj.addDevice(greenFromAbove);
            
            temperature = UnitConvertingDevice('Temperature Controller', 'V', 'manufacturer', 'Warner Instruments').bindStream(daq.getStream('ai6'));
            obj.addDevice(temperature);
            
            trigger = UnitConvertingDevice('Oscilloscope Trigger', Measurement.UNITLESS).bindStream(daq.getStream('doport1'));
            daq.getStream('doport1').setBitPosition(trigger, 0);
            obj.addDevice(trigger);        
        end
        
    end
    
end

